# Generated by Django 5.2.4 on 2025-08-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscription', '0003_subscription_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['advance', 'basic'], 'content_type__app_lable': 'subscription'}, to='auth.permission'),
        ),
    ]
