# Generated by Django 5.2.4 on 2025-08-13 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_uersubsription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UerSubsription',
            new_name='UserSubsription',
        ),
    ]
