# Generated by Django 5.2.4 on 2025-08-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_subscriptionprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
    ]
