# Generated by Django 5.2.4 on 2025-08-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_subscription_options_subscription_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['subscription__order', 'order', 'featured', '-updated']},
        ),
    ]
