# Generated by Django 5.2.4 on 2025-08-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Feature For Pricing by Separated Line', null=True),
        ),
    ]
