# Generated by Django 5.2.4 on 2025-08-15 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_subscription_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubsription',
            new_name='UserSubscription',
        ),
    ]
