# Generated by Django 5.2.4 on 2025-08-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisits',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
